[package]
name = "minecraft"
version = "0.0.1"
authors = ["Roy Wellington Ⅳ <cactus_hugged@yahoo.com>"]

edition = "2018"

[lib]
name = "minecraft"
path = "src/lib.rs"

[dependencies]
byteorder = "^1.2.1"
